=== spacetx/starfish/starfish/spacetx_format/schema/field_of_view_0.1.0/field_of_view.json
{
  "$id": "https://github.com/spacetx/starfish/spacetx_format/schema/field_of_view_0.1.0/field_of_view.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "version",
    "dimensions",
    "shape",
    "tiles"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "$ref": "schema/version.json"
    },
    "extras": {
      "$ref": "schema/extras.json"
    },
    "dimensions": {
      "type": "array",
      "description": "Dimensions of the image tensor described by this fov specification.",
      "minItems": 1,
      "items": {
        "$id": "/properties/dimensions/items",
        "type": "string",
        "description": "A dimension of the tensor described by this fov specification.",
        "examples": [
          "x",
          "y",
          "c",
          "z",
          "r"
        ]
      }
    },
    "shape": {
      "type": "object",
      "description": "The shape of the categorical dimensions (channel, round, z-plane) of the field of view.",
      "required": ["c", "r"],
      "properties": {
        "r": {
          "description": "Number of imaging rounds.",
          "type": "integer",
          "default": 1,
          "minimum": 1,
          "examples": [
            1, 2, 10
          ]
        },
        "c": {
          "type": "integer",
          "description": "Number of channels.",
          "minimum": 1,
          "default": 1,
          "examples": [
            3, 5, 10
          ]
        },
        "z": {
          "type": "integer",
          "title": "Number of z-sections.",
          "minimum": 1,
          "default": 1,
          "examples": [
            1, 34, 67
          ]
        }
      }
    },
    "tiles": {
      "minItems": 1,
      "items": {
        "$ref": "schema/field_of_view_0.1.0/tiles/tiles.json"
      }
    },
    "default_tile_shape": {
      "oneOf": [
        {
          "type": "array",
          "description": "The default tile shape (y, x) of the tiles in this field of view.",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "integer",
            "example": 2048,
            "minimum": 0,
            "maximum": 3000
          }
        },
        {
          "type": "object",
          "description": "The default tile shape of the tiles in this field of view.",
          "properties": {
            "x": {
              "type": "integer",
              "description": "The width of the tile in pixels.",
              "minimum": 1
            },
            "y": {
              "type": "integer",
              "description": "The height of the tile in pixels.",
              "minimum": 1
            }
          },
          "required": [
            "x",
            "y"
          ],
          "additionalProperties": false
        }
      ]
    },
    "default_tile_format": {
      "type": "string",
      "title": "The default tile format for this field of view.",
      "enum": [
        "TIFF",
        "NUMPY"
      ]
    }
  }
}

=== spacetx/starfish/sptx_format/examples/field_of_view/too_large.json
{
  "version": "0.0.0",
  "dimensions": [
      "x",
      "y",
      "z",
      "r",
      "c"
  ],
  "shape": {
      "z": 45,
      "r": 8,
      "c": 2
  },
  "default_tile_format": "TIFF",
  "default_tile_shape": [
    4096,
    4096
  ],
  "extras": "nothing to see here",
  "tiles": [
    {
      "coordinates": {
        "xc": [0.0, 0.1],
        "yc": [0.0, 0.1],
        "zc": [0.0]
      },
      "indices": {
        "z": 0,
        "r": 0,
        "c": 0
      },
      "file": "fdaj3902.tiff",
      "tile_format": "TIFF",
      "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "extras": {
        "are_we_missing_something":"probably"
      }
    },
    {
      "coordinates": {
        "xc": [0.0, 0.1],
        "yc": [0.0, 0.1],
        "zc": [0.1]
      },
      "indices": {
        "z": 1,
        "r": 1,
        "c": 0
      },
      "file": "F_1_Z_1_H_1_C_0.tiff",
      "tile_format": "TIFF",
 	  "sha256": "e3b0c44i98fx1c149afbf4c8996fb924273941e7649b234ca4959a2b7822b855",
      "extras": {
        "are_we_missing_something": "probably"
      }
    }
  ]
}

=== spacetx/starfish/starfish/spacetx_format/examples/field_of_view/dartfish_nuclei.json
{
    "default_tile_shape": [
        1024,
        1024
    ],
    "dimensions": [
        "y",
        "z",
        "r",
        "c",
        "x"
    ],
    "extras": {},
    "shape": {
        "c": 1,
        "r": 1,
        "z": 1
    },
    "tiles": [
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.001
                ],
                "yc": [
                    0.0,
                    0.001
                ],
                "zc": [
                    0.0,
                    0.001
                ]
            },
            "file": "dapi-X0-Y0-Z0-H0-C0.tif",
            "indices": {
                "c": 0,
                "r": 0,
                "z": 0
            },
            "sha256": "185a4b51a244b9a32d27550c3a78d9c44c192b18a24d2379b79fee793766b67e",
            "tile_format": "TIFF",
            "tile_shape": [
                1024,
                1024
            ]
        }
    ],
    "version": "1.0.0"
}
